package com.barberiamimi.gestioncitas.servicio;

import com.barberiamimi.gestioncitas.dto.solicitud.*;
import com.barberiamimi.gestioncitas.dto.respuesta.*;
import com.barberiamimi.gestioncitas.entidad.*;
import com.barberiamimi.gestioncitas.enumeracion.*;
import com.barberiamimi.gestioncitas.excepcion.*;
import com.barberiamimi.gestioncitas.mapper.MapperRespuestas;
import com.barberiamimi.gestioncitas.repositorio.*;
import com.barberiamimi.gestioncitas.seguridad.UsuarioAutenticado;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;
import java.util.*;

@Service
public class ServicioAdministracion {
    private final RepositorioBarberia barberias; private final RepositorioCita citas; private final RepositorioServicio servicios; private final RepositorioProfesional profesionales;
    private final RepositorioHorarioTrabajo horarios; private final RepositorioDiaBloqueado dias; private final RepositorioNotificacion notificaciones; private final RepositorioUsuarioAdministracion usuarios;
    private final RepositorioAuditoriaAdministrativa auditorias; private final MapperRespuestas mapper; private final ServicioDisponibilidad disponibilidad; private final PasswordEncoder codificador;
    public ServicioAdministracion(RepositorioBarberia b,RepositorioCita c,RepositorioServicio s,RepositorioProfesional p,RepositorioHorarioTrabajo h,RepositorioDiaBloqueado d,RepositorioNotificacion n,RepositorioUsuarioAdministracion u,RepositorioAuditoriaAdministrativa a,MapperRespuestas m,ServicioDisponibilidad dis,PasswordEncoder co){barberias=b;citas=c;servicios=s;profesionales=p;horarios=h;dias=d;notificaciones=n;usuarios=u;auditorias=a;mapper=m;disponibilidad=dis;codificador=co;}
    @Transactional(readOnly=true) public List<CitaRespuesta> listarCitas(UsuarioAutenticado u){List<Cita> lista=u.getRol()==RolUsuario.PROPIETARIO?citas.findByBarberiaIdOrderByFechaInicioDesc(u.getBarberiaId()):citas.findByBarberiaIdAndProfesionalIdOrderByFechaInicioDesc(u.getBarberiaId(),u.getProfesionalId());return lista.stream().map(mapper::cita).toList();}
    @Transactional(readOnly=true) public CitaRespuesta consultarCita(UsuarioAutenticado u,Long id){return mapper.cita(obtenerCitaAutorizada(u,id));}
    @Transactional public CitaRespuesta actualizarCita(UsuarioAutenticado u,Long id,SolicitudCrearCita s){Cita c=obtenerCitaAutorizada(u,id);exigirActiva(c);Profesional p=profesionales.findByIdAndBarberiaIdAndActivoTrue(s.profesionalId(),u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El profesional no existe."));if(u.getRol()==RolUsuario.BARBERO&&!p.getId().equals(u.getProfesionalId()))throw new AccesoNoAutorizadoExcepcion("No puedes asignar citas a otro profesional.");Servicio se=servicios.findByIdAndBarberiaIdAndActivoTrue(s.servicioId(),u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El servicio no existe."));LocalDateTime fin=s.fechaInicio().plusMinutes(se.getDuracionMinutos());disponibilidad.validarDisponibleExcluyendo(u.getBarberiaId(),p.getId(),s.fechaInicio(),fin,c.getId());c.actualizarReserva(p,se,s.nombreCliente().trim(),s.telefonoCliente().trim(),s.correoCliente(),s.fechaInicio(),fin,s.notaCliente());auditar(u,"ACTUALIZAR","CITA",c.getId());return mapper.cita(c);}
    @Transactional public CitaRespuesta cambiarEstado(UsuarioAutenticado u,Long id,SolicitudCambiarEstadoCita s){Cita c=obtenerCitaAutorizada(u,id);if(!transicionValida(c.getEstado(),s.estado()))throw new SolicitudInvalidaExcepcion("La transición de estado solicitada no está permitida.");c.setEstado(s.estado());if(s.estado()==EstadoCita.CANCELADA_POR_BARBERIA){c.setCanceladaPor(CanceladaPor.BARBERIA);c.setFechaCancelacion(LocalDateTime.now());c.setMotivoCancelacion(s.motivo());c.setCodigoCancelacionHmac(null);}auditar(u,"CAMBIAR_ESTADO","CITA",id);return mapper.cita(c);}
    @Transactional public CitaRespuesta cancelarCita(UsuarioAutenticado u,Long id,String motivo){return cambiarEstado(u,id,new SolicitudCambiarEstadoCita(EstadoCita.CANCELADA_POR_BARBERIA,motivo));}
    @Transactional(readOnly=true) public List<ServicioRespuesta> listarServicios(UsuarioAutenticado u){return servicios.findByBarberiaIdOrderByNombre(u.getBarberiaId()).stream().map(mapper::servicio).toList();}
    @Transactional public ServicioRespuesta crearServicio(UsuarioAutenticado u,SolicitudServicio s){exigirPropietario(u);if(servicios.existsByBarberiaIdAndNombreIgnoreCase(u.getBarberiaId(),s.nombre()))throw new RecursoDuplicadoExcepcion("Ya existe un servicio con ese nombre.");Servicio creado=servicios.save(new Servicio(barberias.getReferenceById(u.getBarberiaId()),s.nombre().trim(),s.descripcion(),s.precio(),s.duracionMinutos()));auditar(u,"CREAR","SERVICIO",creado.getId());return mapper.servicio(creado);}
    @Transactional public ServicioRespuesta actualizarServicio(UsuarioAutenticado u,Long id,SolicitudServicio s){exigirPropietario(u);Servicio e=servicios.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El servicio no existe."));e.setNombre(s.nombre().trim());e.setDescripcion(s.descripcion());e.setPrecio(s.precio());e.setDuracionMinutos(s.duracionMinutos());auditar(u,"ACTUALIZAR","SERVICIO",id);return mapper.servicio(e);}
    @Transactional public ServicioRespuesta estadoServicio(UsuarioAutenticado u,Long id,boolean activo){exigirPropietario(u);Servicio e=servicios.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El servicio no existe."));e.setActivo(activo);auditar(u,"CAMBIAR_ESTADO","SERVICIO",id);return mapper.servicio(e);}
    @Transactional(readOnly=true) public List<ProfesionalRespuesta> listarProfesionales(UsuarioAutenticado u){return profesionales.findByBarberiaIdOrderByNombre(u.getBarberiaId()).stream().map(mapper::profesional).toList();}
    @Transactional public ProfesionalRespuesta crearProfesional(UsuarioAutenticado u,SolicitudProfesional s){exigirPropietario(u);Profesional p=profesionales.save(new Profesional(barberias.getReferenceById(u.getBarberiaId()),s.nombre().trim(),s.alias()));auditar(u,"CREAR","PROFESIONAL",p.getId());return mapper.profesional(p);}
    @Transactional public ProfesionalRespuesta actualizarProfesional(UsuarioAutenticado u,Long id,SolicitudProfesional s){exigirPropietario(u);Profesional p=profesionales.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El profesional no existe."));p.setNombre(s.nombre().trim());p.setAlias(s.alias());auditar(u,"ACTUALIZAR","PROFESIONAL",id);return mapper.profesional(p);}
    @Transactional public ProfesionalRespuesta estadoProfesional(UsuarioAutenticado u,Long id,boolean activo){exigirPropietario(u);Profesional p=profesionales.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El profesional no existe."));p.setActivo(activo);auditar(u,"CAMBIAR_ESTADO","PROFESIONAL",id);return mapper.profesional(p);}
    @Transactional(readOnly=true) public List<HorarioRespuesta> listarHorarios(UsuarioAutenticado u){return horarios.findByBarberiaIdOrderByDiaSemanaAscHoraInicioAsc(u.getBarberiaId()).stream().filter(h->u.getRol()==RolUsuario.PROPIETARIO||h.getProfesional().getId().equals(u.getProfesionalId())).map(mapper::horario).toList();}
    @Transactional public HorarioRespuesta crearHorario(UsuarioAutenticado u,SolicitudHorario s){Profesional p=obtenerProfesionalGestionable(u,s.profesionalId());validarHoras(s.horaInicio(),s.horaFin());HorarioTrabajo h=horarios.save(new HorarioTrabajo(barberias.getReferenceById(u.getBarberiaId()),p,s.diaSemana(),s.horaInicio(),s.horaFin()));auditar(u,"CREAR","HORARIO",h.getId());return mapper.horario(h);}
    @Transactional public HorarioRespuesta actualizarHorario(UsuarioAutenticado u,Long id,SolicitudHorario s){HorarioTrabajo h=horarios.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El horario no existe."));obtenerProfesionalGestionable(u,h.getProfesional().getId());if(!h.getProfesional().getId().equals(s.profesionalId()))throw new SolicitudInvalidaExcepcion("No se puede cambiar el profesional de un horario.");validarHoras(s.horaInicio(),s.horaFin());h.setDiaSemana(s.diaSemana());h.setHoraInicio(s.horaInicio());h.setHoraFin(s.horaFin());auditar(u,"ACTUALIZAR","HORARIO",id);return mapper.horario(h);}
    @Transactional public void eliminarHorario(UsuarioAutenticado u,Long id){HorarioTrabajo h=horarios.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El horario no existe."));obtenerProfesionalGestionable(u,h.getProfesional().getId());horarios.delete(h);auditar(u,"ELIMINAR","HORARIO",id);}
    @Transactional(readOnly=true) public List<DiaBloqueadoRespuesta> listarDias(UsuarioAutenticado u){return dias.findByBarberiaIdOrderByFechaDesc(u.getBarberiaId()).stream().filter(d->u.getRol()==RolUsuario.PROPIETARIO||d.getProfesional().getId().equals(u.getProfesionalId())).map(mapper::diaBloqueado).toList();}
    @Transactional public DiaBloqueadoRespuesta crearDia(UsuarioAutenticado u,SolicitudDiaBloqueado s){Profesional p=obtenerProfesionalGestionable(u,s.profesionalId());validarFranjaOpcional(s.horaInicio(),s.horaFin());DiaBloqueado d=dias.save(new DiaBloqueado(barberias.getReferenceById(u.getBarberiaId()),p,s.fecha(),s.horaInicio(),s.horaFin(),s.motivo()));auditar(u,"CREAR","DIA_BLOQUEADO",d.getId());return mapper.diaBloqueado(d);}
    @Transactional public DiaBloqueadoRespuesta actualizarDia(UsuarioAutenticado u,Long id,SolicitudDiaBloqueado s){DiaBloqueado d=dias.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El día bloqueado no existe."));obtenerProfesionalGestionable(u,d.getProfesional().getId());if(!d.getProfesional().getId().equals(s.profesionalId()))throw new SolicitudInvalidaExcepcion("No se puede cambiar el profesional del bloqueo.");validarFranjaOpcional(s.horaInicio(),s.horaFin());d.setFecha(s.fecha());d.setHoraInicio(s.horaInicio());d.setHoraFin(s.horaFin());d.setMotivo(s.motivo());auditar(u,"ACTUALIZAR","DIA_BLOQUEADO",id);return mapper.diaBloqueado(d);}
    @Transactional public void eliminarDia(UsuarioAutenticado u,Long id){DiaBloqueado d=dias.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El día bloqueado no existe."));obtenerProfesionalGestionable(u,d.getProfesional().getId());dias.delete(d);auditar(u,"ELIMINAR","DIA_BLOQUEADO",id);}
    @Transactional(readOnly=true) public List<NotificacionRespuesta> listarNotificaciones(UsuarioAutenticado u){return notificaciones.findByBarberiaIdOrderByFechaCreacionDesc(u.getBarberiaId()).stream().filter(n->u.getRol()==RolUsuario.PROPIETARIO||n.getProfesional()==null||n.getProfesional().getId().equals(u.getProfesionalId())).map(mapper::notificacion).toList();}
    @Transactional public NotificacionRespuesta marcarLeida(UsuarioAutenticado u,Long id){Notificacion n=notificaciones.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("La notificación no existe."));if(u.getRol()==RolUsuario.BARBERO&&n.getProfesional()!=null&&!n.getProfesional().getId().equals(u.getProfesionalId()))throw new AccesoNoAutorizadoExcepcion("No puedes consultar esa notificación.");n.marcarLeida();return mapper.notificacion(n);}
    @Transactional public UsuarioRespuesta crearUsuario(UsuarioAutenticado u,SolicitudCrearUsuario s){exigirPropietario(u);if(usuarios.findByNombreUsuario(s.nombreUsuario()).isPresent())throw new RecursoDuplicadoExcepcion("El nombre de usuario ya existe.");Profesional p=s.profesionalId()==null?null:profesionales.findByIdAndBarberiaId(s.profesionalId(),u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El profesional no existe."));if(s.rol()==RolUsuario.BARBERO&&p==null)throw new SolicitudInvalidaExcepcion("Un usuario BARBERO debe estar asociado a un profesional.");UsuarioAdministracion creado=usuarios.save(new UsuarioAdministracion(barberias.getReferenceById(u.getBarberiaId()),p,s.nombreUsuario().trim(),codificador.encode(s.contrasena()),s.rol()));auditar(u,"CREAR","USUARIO",creado.getId());return new UsuarioRespuesta(creado.getId(),creado.getNombreUsuario(),creado.getRol(),p==null?null:p.getId(),creado.isActivo());}
    @Transactional public MensajeRespuesta cambiarContrasena(UsuarioAutenticado u,Long id,SolicitudCambiarContrasena s){exigirPropietario(u);UsuarioAdministracion usuario=usuarios.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El usuario no existe."));usuario.setContrasenaHash(codificador.encode(s.nuevaContrasena()));usuario.setIntentosFallidos(0);usuario.setFechaBloqueo(null);auditar(u,"CAMBIAR_CONTRASENA","USUARIO",id);return new MensajeRespuesta("CONTRASENA_ACTUALIZADA","La contraseña se ha actualizado correctamente.");}
    private Cita obtenerCitaAutorizada(UsuarioAutenticado u,Long id){Cita c=citas.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("La cita no existe."));if(u.getRol()==RolUsuario.BARBERO&&!c.getProfesional().getId().equals(u.getProfesionalId()))throw new AccesoNoAutorizadoExcepcion("No puedes acceder a citas de otro profesional.");return c;}
    private Profesional obtenerProfesionalGestionable(UsuarioAutenticado u,Long id){Profesional p=profesionales.findByIdAndBarberiaId(id,u.getBarberiaId()).orElseThrow(()->new RecursoNoEncontradoExcepcion("El profesional no existe."));if(u.getRol()==RolUsuario.BARBERO&&!id.equals(u.getProfesionalId()))throw new AccesoNoAutorizadoExcepcion("No puedes gestionar a otro profesional.");return p;}
    private void exigirPropietario(UsuarioAutenticado u){if(u.getRol()!=RolUsuario.PROPIETARIO)throw new AccesoNoAutorizadoExcepcion("La operación requiere el rol PROPIETARIO.");}
    private void exigirActiva(Cita c){if(!c.estaActiva())throw new SolicitudInvalidaExcepcion("Solo se pueden modificar citas activas.");}
    private void validarHoras(java.time.LocalTime inicio,java.time.LocalTime fin){if(!fin.isAfter(inicio))throw new SolicitudInvalidaExcepcion("La hora final debe ser posterior a la inicial.");}
    private void validarFranjaOpcional(java.time.LocalTime inicio,java.time.LocalTime fin){if((inicio==null)!=(fin==null))throw new SolicitudInvalidaExcepcion("La franja debe indicar ambas horas o ninguna.");if(inicio!=null)validarHoras(inicio,fin);}
    private boolean transicionValida(EstadoCita origen,EstadoCita destino){if(origen==destino)return true;if(origen==EstadoCita.RESERVADA)return destino==EstadoCita.CONFIRMADA||destino==EstadoCita.CANCELADA_POR_BARBERIA;if(origen==EstadoCita.CONFIRMADA)return destino==EstadoCita.COMPLETADA||destino==EstadoCita.NO_PRESENTADO||destino==EstadoCita.CANCELADA_POR_BARBERIA;return false;}
    private void auditar(UsuarioAutenticado u,String accion,String tipo,Long id){UsuarioAdministracion usuario=usuarios.getReferenceById(u.getId());auditorias.save(new AuditoriaAdministrativa(barberias.getReferenceById(u.getBarberiaId()),usuario,accion,tipo,id));}
}
