package com.barberiamimi.gestioncitas.servicio;

import com.barberiamimi.gestioncitas.dto.solicitud.*;
import com.barberiamimi.gestioncitas.entidad.*;
import com.barberiamimi.gestioncitas.enumeracion.*;
import com.barberiamimi.gestioncitas.excepcion.AccesoNoAutorizadoExcepcion;
import com.barberiamimi.gestioncitas.mapper.MapperRespuestas;
import com.barberiamimi.gestioncitas.repositorio.*;
import com.barberiamimi.gestioncitas.seguridad.UsuarioAutenticado;
import org.junit.jupiter.api.*;
import org.springframework.security.crypto.password.PasswordEncoder;
import java.lang.reflect.Field;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

class ServicioAdministracionPrueba {
 private final RepositorioBarberia barberias=mock(RepositorioBarberia.class);private final RepositorioCita citas=mock(RepositorioCita.class);private final RepositorioServicio servicios=mock(RepositorioServicio.class);private final RepositorioProfesional profesionales=mock(RepositorioProfesional.class);private final RepositorioHorarioTrabajo horarios=mock(RepositorioHorarioTrabajo.class);private final RepositorioDiaBloqueado dias=mock(RepositorioDiaBloqueado.class);private final RepositorioNotificacion notificaciones=mock(RepositorioNotificacion.class);private final RepositorioUsuarioAdministracion usuarios=mock(RepositorioUsuarioAdministracion.class);private final RepositorioAuditoriaAdministrativa auditorias=mock(RepositorioAuditoriaAdministrativa.class);private final ServicioDisponibilidad disponibilidad=mock(ServicioDisponibilidad.class);private final PasswordEncoder codificador=mock(PasswordEncoder.class);
 private ServicioAdministracion servicio;private Barberia barberia;private Profesional mimi;private Servicio corte;private Cita cita;private UsuarioAdministracion usuarioEntidad;private UsuarioAutenticado propietario;private UsuarioAutenticado barbero;
 @BeforeEach void preparar()throws Exception{reset(barberias,citas,servicios,profesionales,horarios,dias,notificaciones,usuarios,auditorias,disponibilidad,codificador);barberia=new Barberia("Barbería Mimi","barberia-mimi");id(barberia,1L);mimi=new Profesional(barberia,"Mimi","mimi");id(mimi,2L);corte=new Servicio(barberia,"Corte",null,new BigDecimal("15.00"),30);id(corte,3L);cita=new Cita(barberia,mimi,corte,"Ana","600123123",null,LocalDateTime.now().plusDays(3),LocalDateTime.now().plusDays(3).plusMinutes(30),null,"hmac","clave","huella");id(cita,4L);usuarioEntidad=new UsuarioAdministracion(barberia,mimi,"duena","hash",RolUsuario.PROPIETARIO);id(usuarioEntidad,9L);propietario=principal(RolUsuario.PROPIETARIO,2L);barbero=principal(RolUsuario.BARBERO,2L);when(barberias.getReferenceById(1L)).thenReturn(barberia);when(usuarios.getReferenceById(9L)).thenReturn(usuarioEntidad);when(codificador.encode(anyString())).thenReturn("hash-nuevo");servicio=new ServicioAdministracion(barberias,citas,servicios,profesionales,horarios,dias,notificaciones,usuarios,auditorias,new MapperRespuestas(),disponibilidad,codificador);}
 @Test @DisplayName("Debe aislar citas por barbería y profesional según el rol") void debeAislarCitas(){when(citas.findByBarberiaIdOrderByFechaInicioDesc(1L)).thenReturn(List.of(cita));when(citas.findByBarberiaIdAndProfesionalIdOrderByFechaInicioDesc(1L,2L)).thenReturn(List.of(cita));when(citas.findByIdAndBarberiaId(4L,1L)).thenReturn(Optional.of(cita));assertEquals(1,servicio.listarCitas(propietario).size());assertEquals(1,servicio.listarCitas(barbero).size());assertEquals(4L,servicio.consultarCita(barbero,4L).id());Profesional otro=new Profesional(barberia,"Otro","otro");try{id(otro,20L);Cita ajena=new Cita(barberia,otro,corte,"B","600111111",null,LocalDateTime.now().plusDays(4),LocalDateTime.now().plusDays(4).plusMinutes(30),null,"h","k","x");id(ajena,21L);when(citas.findByIdAndBarberiaId(21L,1L)).thenReturn(Optional.of(ajena));assertThrows(AccesoNoAutorizadoExcepcion.class,()->servicio.consultarCita(barbero,21L));}catch(Exception e){throw new RuntimeException(e);}}
 @Test @DisplayName("Debe actualizar y completar una cita autorizada") void debeGestionarCita(){when(citas.findByIdAndBarberiaId(4L,1L)).thenReturn(Optional.of(cita));when(profesionales.findByIdAndBarberiaIdAndActivoTrue(2L,1L)).thenReturn(Optional.of(mimi));when(servicios.findByIdAndBarberiaIdAndActivoTrue(3L,1L)).thenReturn(Optional.of(corte));SolicitudCrearCita cambio=new SolicitudCrearCita("Ana María","600123123",null,3L,2L,LocalDateTime.now().plusDays(5),null);assertEquals("Ana María",servicio.actualizarCita(propietario,4L,cambio).id()!=null?cita.getNombreCliente():"");assertEquals(EstadoCita.COMPLETADA,servicio.cambiarEstado(propietario,4L,new SolicitudCambiarEstadoCita(EstadoCita.COMPLETADA,null)).estado());verify(disponibilidad).validarDisponibleExcluyendo(eq(1L),eq(2L),any(),any(),eq(4L));}
 @Test @DisplayName("Debe cancelar administrativamente sin aplicar el plazo público") void debeCancelarAdministrativamente(){when(citas.findByIdAndBarberiaId(4L,1L)).thenReturn(Optional.of(cita));var r=servicio.cancelarCita(propietario,4L,"Cierre especial");assertEquals(EstadoCita.CANCELADA_POR_BARBERIA,r.estado());assertEquals(CanceladaPor.BARBERIA,r.canceladaPor());assertNotNull(r.fechaCancelacion());}
 @Test @DisplayName("El propietario debe gestionar servicios y profesionales") void debeGestionarCatalogo()throws Exception{when(servicios.findByBarberiaIdOrderByNombre(1L)).thenReturn(List.of(corte));when(servicios.save(any())).thenAnswer(i->{Servicio s=i.getArgument(0);id(s,30L);return s;});when(servicios.findByIdAndBarberiaId(3L,1L)).thenReturn(Optional.of(corte));assertEquals(1,servicio.listarServicios(propietario).size());var creado=servicio.crearServicio(propietario,new SolicitudServicio("Barba",null,new BigDecimal("10"),20));assertEquals(30L,creado.id());assertEquals(new BigDecimal("17"),servicio.actualizarServicio(propietario,3L,new SolicitudServicio("Corte",null,new BigDecimal("17"),35)).precio());assertFalse(servicio.estadoServicio(propietario,3L,false).activo());when(profesionales.findByBarberiaIdOrderByNombre(1L)).thenReturn(List.of(mimi));when(profesionales.save(any())).thenAnswer(i->{Profesional p=i.getArgument(0);id(p,31L);return p;});when(profesionales.findByIdAndBarberiaId(2L,1L)).thenReturn(Optional.of(mimi));assertEquals(1,servicio.listarProfesionales(propietario).size());assertEquals(31L,servicio.crearProfesional(propietario,new SolicitudProfesional("Lola","lola")).id());assertEquals("Mimi nueva",servicio.actualizarProfesional(propietario,2L,new SolicitudProfesional("Mimi nueva","mimi")).nombre());assertFalse(servicio.estadoProfesional(propietario,2L,false).activo());assertThrows(AccesoNoAutorizadoExcepcion.class,()->servicio.crearServicio(barbero,new SolicitudServicio("X",null,BigDecimal.ONE,10)));}
 @Test @DisplayName("Debe gestionar horarios y bloqueos solo del profesional autorizado") void debeGestionarAgenda()throws Exception{HorarioTrabajo h=new HorarioTrabajo(barberia,mimi,DayOfWeek.MONDAY,LocalTime.of(9,0),LocalTime.of(14,0));id(h,40L);when(horarios.findByBarberiaIdOrderByDiaSemanaAscHoraInicioAsc(1L)).thenReturn(List.of(h));when(profesionales.findByIdAndBarberiaId(2L,1L)).thenReturn(Optional.of(mimi));when(horarios.save(any())).thenAnswer(i->{HorarioTrabajo x=i.getArgument(0);id(x,41L);return x;});when(horarios.findByIdAndBarberiaId(40L,1L)).thenReturn(Optional.of(h));assertEquals(1,servicio.listarHorarios(barbero).size());assertEquals(41L,servicio.crearHorario(barbero,new SolicitudHorario(2L,DayOfWeek.TUESDAY,LocalTime.of(9,0),LocalTime.of(13,0))).id());assertEquals(DayOfWeek.WEDNESDAY,servicio.actualizarHorario(barbero,40L,new SolicitudHorario(2L,DayOfWeek.WEDNESDAY,LocalTime.of(10,0),LocalTime.of(14,0))).diaSemana());servicio.eliminarHorario(barbero,40L);verify(horarios).delete(h);DiaBloqueado d=new DiaBloqueado(barberia,mimi,LocalDate.now().plusDays(10),null,null,"Vacaciones");id(d,50L);when(dias.findByBarberiaIdOrderByFechaDesc(1L)).thenReturn(List.of(d));when(dias.save(any())).thenAnswer(i->{DiaBloqueado x=i.getArgument(0);id(x,51L);return x;});when(dias.findByIdAndBarberiaId(50L,1L)).thenReturn(Optional.of(d));assertEquals(1,servicio.listarDias(barbero).size());assertEquals(51L,servicio.crearDia(barbero,new SolicitudDiaBloqueado(2L,LocalDate.now().plusDays(20),null,null,"Cierre")).id());assertEquals("Descanso",servicio.actualizarDia(barbero,50L,new SolicitudDiaBloqueado(2L,LocalDate.now().plusDays(11),LocalTime.of(11,0),LocalTime.of(12,0),"Descanso")).motivo());servicio.eliminarDia(barbero,50L);verify(dias).delete(d);}
 @Test @DisplayName("Debe gestionar notificaciones y usuarios de la barbería") void debeGestionarNotificacionesYUsuarios()throws Exception{Notificacion n=new Notificacion(barberia,mimi,cita,TipoNotificacion.CITA_CREADA,"Cita","Creada");id(n,60L);when(notificaciones.findByBarberiaIdOrderByFechaCreacionDesc(1L)).thenReturn(List.of(n));when(notificaciones.findByIdAndBarberiaId(60L,1L)).thenReturn(Optional.of(n));assertEquals(1,servicio.listarNotificaciones(barbero).size());assertTrue(servicio.marcarLeida(barbero,60L).leida());when(profesionales.findByIdAndBarberiaId(2L,1L)).thenReturn(Optional.of(mimi));when(usuarios.save(any())).thenAnswer(i->{UsuarioAdministracion x=i.getArgument(0);id(x,61L);return x;});assertEquals(61L,servicio.crearUsuario(propietario,new SolicitudCrearUsuario("barbero2","contrasena-segura",RolUsuario.BARBERO,2L)).id());when(usuarios.findByIdAndBarberiaId(61L,1L)).thenReturn(Optional.of(usuarioEntidad));assertEquals("CONTRASENA_ACTUALIZADA",servicio.cambiarContrasena(propietario,61L,new SolicitudCambiarContrasena("otra-contrasena-segura")).codigo());assertEquals("hash-nuevo",usuarioEntidad.getContrasenaHash());}
 private UsuarioAutenticado principal(RolUsuario rol,Long profesionalId){return new UsuarioAutenticado(9L,1L,"Barbería Mimi","barberia-mimi",profesionalId,"Mimi","usuario","hash",rol,true,true);}
 private static void id(Object o,Long valor)throws Exception{Field f=o.getClass().getDeclaredField("id");f.setAccessible(true);f.set(o,valor);}
}
