package com.barberiamimi.gestioncitas.servicio;

import com.barberiamimi.gestioncitas.dto.solicitud.*;
import com.barberiamimi.gestioncitas.entidad.*;
import com.barberiamimi.gestioncitas.enumeracion.*;
import com.barberiamimi.gestioncitas.excepcion.AccesoNoAutorizadoExcepcion;
import com.barberiamimi.gestioncitas.mapper.MapperRespuestas;
import com.barberiamimi.gestioncitas.repositorio.*;
import com.barberiamimi.gestioncitas.seguridad.UsuarioAutenticado;
import org.junit.jupiter.api.*;
import org.springframework.security.crypto.password.PasswordEncoder;
import java.lang.reflect.Field;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

class ServicioAdministracionPrueba {
 private final RepositorioBarberia barberias=mock(RepositorioBarberia.class);private final RepositorioCita citas=mock(RepositorioCita.class);private final RepositorioServicio servicios=mock(RepositorioServicio.class);private final RepositorioProfesional profesionales=mock(RepositorioProfesional.class);private final RepositorioHorarioTrabajo horarios=mock(RepositorioHorarioTrabajo.class);private final RepositorioDiaBloqueado dias=mock(RepositorioDiaBloqueado.class);private final RepositorioDiaTrabajoEspecial trabajosEspeciales=mock(RepositorioDiaTrabajoEspecial.class);private final RepositorioNotificacion notificaciones=mock(RepositorioNotificacion.class);private final RepositorioUsuarioAdministracion usuarios=mock(RepositorioUsuarioAdministracion.class);private final RepositorioAuditoriaAdministrativa auditorias=mock(RepositorioAuditoriaAdministrativa.class);private final ServicioDisponibilidad disponibilidad=mock(ServicioDisponibilidad.class);private final PasswordEncoder codificador=mock(PasswordEncoder.class);
 private ServicioAdministracion servicio;private Barberia barberia;private Profesional mimi;private Servicio corte;private Cita cita;private UsuarioAdministracion usuarioEntidad;private UsuarioAutenticado propietario;private UsuarioAutenticado barbero;
 @BeforeEach void preparar()throws Exception{reset(barberias,citas,servicios,profesionales,horarios,dias,trabajosEspeciales,notificaciones,usuarios,auditorias,disponibilidad,codificador);barberia=new Barberia("Barbería Mimi","barberia-mimi");id(barberia,1L);mimi=new Profesional(barberia,"Mimi","mimi");id(mimi,2L);corte=new Servicio(barberia,"Corte",null,new BigDecimal("15.00"),30);id(corte,3L);cita=new Cita(barberia,mimi,corte,"Ana","600123123",LocalDateTime.now().plusDays(3),LocalDateTime.now().plusDays(3).plusMinutes(30),null,"hmac","clave","huella");id(cita,4L);usuarioEntidad=new UsuarioAdministracion(barberia,mimi,"duena","hash",RolUsuario.PROPIETARIO);id(usuarioEntidad,9L);propietario=principal(RolUsuario.PROPIETARIO,2L);barbero=principal(RolUsuario.BARBERO,2L);when(barberias.getReferenceById(1L)).thenReturn(barberia);when(usuarios.getReferenceById(9L)).thenReturn(usuarioEntidad);when(codificador.encode(anyString())).thenReturn("hash-nuevo");servicio=new ServicioAdministracion(barberias,citas,servicios,profesionales,horarios,dias,trabajosEspeciales,notificaciones,usuarios,auditorias,new MapperRespuestas(),disponibilidad,codificador);}
 @Test @DisplayName("Debe aislar citas por barbería y profesional según el rol") void debeAislarCitas(){when(citas.findByBarberiaIdOrderByFechaInicioDesc(1L)).thenReturn(List.of(cita));when(citas.findByBarberiaIdAndProfesionalIdOrderByFechaInicioDesc(1L,2L)).thenReturn(List.of(cita));when(citas.findByIdAndBarberiaId(4L,1L)).thenReturn(Optional.of(cita));assertEquals(1,servicio.listarCitas(propietario).size());assertEquals(1,servicio.listarCitas(barbero).size());assertEquals(4L,servicio.consultarCita(barbero,4L).id());Profesional otro=new Profesional(barberia,"Otro","otro");try{id(otro,20L);Cita ajena=new Cita(barberia,otro,corte,"B","600111111",LocalDateTime.now().plusDays(4),LocalDateTime.now().plusDays(4).plusMinutes(30),null,"h","k","x");id(ajena,21L);when(citas.findByIdAndBarberiaId(21L,1L)).thenReturn(Optional.of(ajena));assertThrows(AccesoNoAutorizadoExcepcion.class,()->servicio.consultarCita(barbero,21L));}catch(Exception e){throw new RuntimeException(e);}}
 @Test @DisplayName("Debe actualizar y completar una cita autorizada") void debeGestionarCita(){when(citas.findByIdAndBarberiaId(4L,1L)).thenReturn(Optional.of(cita));when(profesionales.findByIdAndBarberiaIdAndActivoTrue(2L,1L)).thenReturn(Optional.of(mimi));when(servicios.findByIdAndBarberiaIdAndActivoTrue(3L,1L)).thenReturn(Optional.of(corte));SolicitudCrearCita cambio=new SolicitudCrearCita("Ana María","600123123",3L,2L,LocalDateTime.now().plusDays(5),null);assertEquals("Ana María",servicio.actualizarCita(propietario,4L,cambio).id()!=null?cita.getNombreCliente():"");assertEquals(EstadoCita.COMPLETADA,servicio.cambiarEstado(propietario,4L,new SolicitudCambiarEstadoCita(EstadoCita.COMPLETADA,null)).estado());verify(disponibilidad).validarDisponibleExcluyendo(eq(1L),eq(2L),any(),any(),eq(4L));}
 @Test @DisplayName("No debe permitir el estado no presentado") void debeRechazarNoPresentado(){when(citas.findByIdAndBarberiaId(4L,1L)).thenReturn(Optional.of(cita));assertThrows(com.barberiamimi.gestioncitas.excepcion.SolicitudInvalidaExcepcion.class,()->servicio.cambiarEstado(propietario,4L,new SolicitudCambiarEstadoCita(EstadoCita.NO_PRESENTADO,null)));}
 @Test @DisplayName("Debe cancelar administrativamente sin aplicar el plazo público") void debeCancelarAdministrativamente(){when(citas.findByIdAndBarberiaId(4L,1L)).thenReturn(Optional.of(cita));var r=servicio.cancelarCita(propietario,4L,"Cierre especial");assertEquals(EstadoCita.CANCELADA_POR_BARBERIA,r.estado());assertEquals(CanceladaPor.BARBERIA,r.canceladaPor());assertNotNull(r.fechaCancelacion());}
 @Test @DisplayName("El propietario debe gestionar servicios y profesionales") void debeGestionarCatalogo()throws Exception{when(servicios.findByBarberiaIdOrderByNombre(1L)).thenReturn(List.of(corte));when(servicios.save(any())).thenAnswer(i->{Servicio s=i.getArgument(0);id(s,30L);return s;});when(servicios.findByIdAndBarberiaId(3L,1L)).thenReturn(Optional.of(corte));assertEquals(1,servicio.listarServicios(propietario).size());var creado=servicio.crearServicio(propietario,new SolicitudServicio("Barba",null,new BigDecimal("10")));assertEquals(30L,creado.id());assertEquals(new BigDecimal("17"),servicio.actualizarServicio(propietario,3L,new SolicitudServicio("Corte",null,new BigDecimal("17"))).precio());assertFalse(servicio.estadoServicio(propietario,3L,false).activo());when(profesionales.findByBarberiaIdOrderByNombre(1L)).thenReturn(List.of(mimi));when(profesionales.save(any())).thenAnswer(i->{Profesional p=i.getArgument(0);id(p,31L);return p;});when(usuarios.save(any())).thenAnswer(i->{UsuarioAdministracion x=i.getArgument(0);id(x,32L);return x;});when(profesionales.findByIdAndBarberiaId(2L,1L)).thenReturn(Optional.of(mimi));assertEquals(1,servicio.listarProfesionales(propietario).size());var profesionalCreado=servicio.crearProfesional(propietario,new SolicitudCrearProfesional("Lola","lola","lola.agenda","contrasena-segura"));assertEquals(31L,profesionalCreado.id());assertEquals("lola.agenda",profesionalCreado.nombreUsuario());assertEquals(RolUsuario.BARBERO,profesionalCreado.rol());assertEquals("Mimi nueva",servicio.actualizarProfesional(propietario,2L,new SolicitudActualizarProfesional("Mimi nueva","mimi","mimi.nuevo","otra-contrasena")).nombre());assertFalse(servicio.estadoProfesional(propietario,2L,false).activo());assertThrows(AccesoNoAutorizadoExcepcion.class,()->servicio.crearServicio(barbero,new SolicitudServicio("X",null,BigDecimal.ONE)));}
 @Test @DisplayName("Debe gestionar horarios y bloqueos solo del profesional autorizado") void debeGestionarAgenda()throws Exception{HorarioTrabajo h=new HorarioTrabajo(barberia,mimi,DayOfWeek.MONDAY,LocalTime.of(9,0),LocalTime.of(14,0));id(h,40L);when(horarios.findByBarberiaIdOrderByDiaSemanaAscHoraInicioAsc(1L)).thenReturn(List.of(h));when(profesionales.findByIdAndBarberiaId(2L,1L)).thenReturn(Optional.of(mimi));when(horarios.save(any())).thenAnswer(i->{HorarioTrabajo x=i.getArgument(0);id(x,41L);return x;});when(horarios.findByIdAndBarberiaId(40L,1L)).thenReturn(Optional.of(h));assertEquals(1,servicio.listarHorarios(barbero).size());assertEquals(41L,servicio.crearHorario(barbero,new SolicitudHorario(2L,DayOfWeek.TUESDAY,LocalTime.of(9,0),LocalTime.of(13,0))).id());assertEquals(DayOfWeek.WEDNESDAY,servicio.actualizarHorario(barbero,40L,new SolicitudHorario(2L,DayOfWeek.WEDNESDAY,LocalTime.of(10,0),LocalTime.of(14,0))).diaSemana());servicio.eliminarHorario(barbero,40L);verify(horarios).delete(h);DiaBloqueado d=new DiaBloqueado(barberia,mimi,LocalDate.now().plusDays(10),null,null,"Vacaciones");id(d,50L);when(dias.findByBarberiaIdOrderByFechaDesc(1L)).thenReturn(List.of(d));when(dias.save(any())).thenAnswer(i->{DiaBloqueado x=i.getArgument(0);id(x,51L);return x;});when(dias.findByIdAndBarberiaId(50L,1L)).thenReturn(Optional.of(d));assertEquals(1,servicio.listarDias(barbero).size());assertEquals(51L,servicio.crearDia(barbero,new SolicitudDiaBloqueado(2L,LocalDate.now().plusDays(20),null,null,"Cierre")).id());assertEquals("Descanso",servicio.actualizarDia(barbero,50L,new SolicitudDiaBloqueado(2L,LocalDate.now().plusDays(11),LocalTime.of(11,0),LocalTime.of(12,0),"Descanso")).motivo());servicio.eliminarDia(barbero,50L);verify(dias).delete(d);}
 @Test @DisplayName("Debe gestionar notificaciones y usuarios de la barbería") void debeGestionarNotificacionesYUsuarios()throws Exception{Notificacion n=new Notificacion(barberia,mimi,cita,TipoNotificacion.CITA_CREADA,"Cita","Creada");id(n,60L);when(notificaciones.findByBarberiaIdOrderByFechaCreacionDesc(1L)).thenReturn(List.of(n));when(notificaciones.findByIdAndBarberiaId(60L,1L)).thenReturn(Optional.of(n));assertEquals(1,servicio.listarNotificaciones(barbero).size());assertTrue(servicio.marcarLeida(barbero,60L).leida());when(profesionales.findByIdAndBarberiaId(2L,1L)).thenReturn(Optional.of(mimi));when(usuarios.save(any())).thenAnswer(i->{UsuarioAdministracion x=i.getArgument(0);id(x,61L);return x;});assertEquals(61L,servicio.crearUsuario(propietario,new SolicitudCrearUsuario("barbero2","contrasena-segura",RolUsuario.BARBERO,2L)).id());when(usuarios.findByIdAndBarberiaId(61L,1L)).thenReturn(Optional.of(usuarioEntidad));assertEquals("CONTRASENA_ACTUALIZADA",servicio.cambiarContrasena(propietario,61L,new SolicitudCambiarContrasena("otra-contrasena-segura")).codigo());assertEquals("hash-nuevo",usuarioEntidad.getContrasenaHash());}
 @Test @DisplayName("El propietario debe configurar la reserva y abrir días especiales") void debeConfigurarCalendario()throws Exception{when(barberias.findById(1L)).thenReturn(Optional.of(barberia));var configuracion=servicio.actualizarConfiguracionReservas(propietario,new SolicitudConfiguracionReservas(45,60));assertEquals(45,configuracion.intervaloMinutos());assertEquals(60,configuracion.diasAntelacionReserva());when(profesionales.findByIdAndBarberiaId(2L,1L)).thenReturn(Optional.of(mimi));when(trabajosEspeciales.findByBarberiaIdAndProfesionalIdAndFechaOrderByHoraInicio(eq(1L),eq(2L),any())).thenReturn(List.of());when(trabajosEspeciales.save(any())).thenAnswer(i->{DiaTrabajoEspecial d=i.getArgument(0);id(d,70L);return d;});var dia=servicio.crearTrabajoEspecial(propietario,new SolicitudDiaTrabajoEspecial(2L,LocalDate.now().plusDays(7),LocalTime.of(9,0),LocalTime.of(13,0)));assertEquals(70L,dia.id());}
 @Test @DisplayName("El propietario debe editar el perfil público y decidir si muestra la ubicación") void debeActualizarPerfilPublico(){when(barberias.findById(1L)).thenReturn(Optional.of(barberia));var resultado=servicio.actualizarPerfilBarberia(propietario,new SolicitudPerfilBarberia("Barbería Mimi","600123123","@mimi","C. Pastores, 1A","https://maps.google.com/mimi",true));assertEquals("@mimi",resultado.instagram());assertEquals("C. Pastores, 1A",resultado.direccion());assertTrue(resultado.mostrarUbicacion());assertThrows(AccesoNoAutorizadoExcepcion.class,()->servicio.consultarPerfilBarberia(barbero));}
 @Test @DisplayName("Debe consultar, actualizar y eliminar días de trabajo especiales") void debeGestionarDiasEspeciales()throws Exception{LocalDate fechaEspecial=LocalDate.now().plusDays(8);DiaTrabajoEspecial especial=new DiaTrabajoEspecial(barberia,mimi,fechaEspecial,LocalTime.of(9,0),LocalTime.of(13,0));id(especial,70L);when(barberias.findById(1L)).thenReturn(Optional.of(barberia));assertEquals(30,servicio.consultarConfiguracionReservas(propietario).intervaloMinutos());when(trabajosEspeciales.findByBarberiaIdOrderByFechaAscHoraInicioAsc(1L)).thenReturn(List.of(especial));assertEquals(1,servicio.listarTrabajosEspeciales(propietario).size());assertEquals(1,servicio.listarTrabajosEspeciales(barbero).size());when(trabajosEspeciales.findByIdAndBarberiaId(70L,1L)).thenReturn(Optional.of(especial));when(profesionales.findByIdAndBarberiaId(2L,1L)).thenReturn(Optional.of(mimi));when(trabajosEspeciales.findByBarberiaIdAndProfesionalIdAndFechaOrderByHoraInicio(1L,2L,fechaEspecial)).thenReturn(List.of(especial));var actualizado=servicio.actualizarTrabajoEspecial(barbero,70L,new SolicitudDiaTrabajoEspecial(2L,fechaEspecial,LocalTime.of(10,0),LocalTime.of(14,0)));assertEquals(LocalTime.of(10,0),actualizado.horaInicio());servicio.eliminarTrabajoEspecial(barbero,70L);verify(trabajosEspeciales).delete(especial);}
 @Test @DisplayName("Debe impedir abrir un día marcado como descanso") void debeImpedirTrabajoEspecialEnDescanso(){LocalDate fechaEspecial=LocalDate.now().plusDays(9);when(profesionales.findByIdAndBarberiaId(2L,1L)).thenReturn(Optional.of(mimi));when(dias.findByBarberiaIdAndProfesionalIdAndFecha(1L,2L,fechaEspecial)).thenReturn(List.of(new DiaBloqueado(barberia,mimi,fechaEspecial,null,null,"Descanso")));assertThrows(com.barberiamimi.gestioncitas.excepcion.SolicitudInvalidaExcepcion.class,()->servicio.crearTrabajoEspecial(propietario,new SolicitudDiaTrabajoEspecial(2L,fechaEspecial,LocalTime.of(9,0),LocalTime.of(13,0))));verify(trabajosEspeciales,never()).save(any());}
 @Test @DisplayName("Un bloqueo parcial debe cancelar citas y crear el aviso de contacto") void debeBloquearFranjaYCancelarCita()throws Exception{LocalDate fechaBloqueo=LocalDate.now().plusDays(3);HorarioTrabajo jornada=new HorarioTrabajo(barberia,mimi,fechaBloqueo.getDayOfWeek(),LocalTime.of(9,0),LocalTime.of(14,0));when(profesionales.findByIdAndBarberiaId(2L,1L)).thenReturn(Optional.of(mimi));when(dias.findByBarberiaIdAndProfesionalIdAndFecha(1L,2L,fechaBloqueo)).thenReturn(List.of());when(trabajosEspeciales.findByBarberiaIdAndProfesionalIdAndFechaOrderByHoraInicio(1L,2L,fechaBloqueo)).thenReturn(List.of());when(horarios.findByBarberiaIdAndProfesionalIdAndDiaSemanaAndActivoTrueOrderByHoraInicio(1L,2L,fechaBloqueo.getDayOfWeek())).thenReturn(List.of(jornada));when(dias.save(any())).thenAnswer(i->{DiaBloqueado d=i.getArgument(0);id(d,80L);return d;});when(citas.buscarSolapamientos(eq(1L),eq(2L),any(),any())).thenReturn(List.of(cita));var respuesta=servicio.crearBloqueoParcial(propietario,new SolicitudBloqueoParcial(2L,fechaBloqueo,LocalTime.of(10,0),LocalTime.of(10,30),"Gestión personal"));assertEquals(1,respuesta.citasCanceladas());assertEquals("600123123",respuesta.citasAfectadas().getFirst().telefonoCliente());assertEquals(EstadoCita.CANCELADA_POR_BARBERIA,cita.getEstado());verify(notificaciones).save(any(Notificacion.class));}
 @Test @DisplayName("Varios tramos deben guardarse juntos y agrupar las citas afectadas") void debeBloquearVariosTramos()throws Exception{LocalDate fechaBloqueo=LocalDate.now().plusDays(3);HorarioTrabajo jornada=new HorarioTrabajo(barberia,mimi,fechaBloqueo.getDayOfWeek(),LocalTime.of(9,0),LocalTime.of(14,0));when(profesionales.findByIdAndBarberiaId(2L,1L)).thenReturn(Optional.of(mimi));when(dias.findByBarberiaIdAndProfesionalIdAndFecha(1L,2L,fechaBloqueo)).thenReturn(List.of());when(trabajosEspeciales.findByBarberiaIdAndProfesionalIdAndFechaOrderByHoraInicio(1L,2L,fechaBloqueo)).thenReturn(List.of());when(horarios.findByBarberiaIdAndProfesionalIdAndDiaSemanaAndActivoTrueOrderByHoraInicio(1L,2L,fechaBloqueo.getDayOfWeek())).thenReturn(List.of(jornada));when(dias.save(any())).thenAnswer(i->{DiaBloqueado d=i.getArgument(0);id(d,80L);return d;});when(citas.buscarSolapamientos(eq(1L),eq(2L),any(),any())).thenReturn(List.of(cita),List.of());var respuesta=servicio.crearBloqueosParciales(propietario,new SolicitudBloqueosParciales(2L,fechaBloqueo,List.of(new FranjaBloqueoSolicitud(LocalTime.of(10,0),LocalTime.of(10,30)),new FranjaBloqueoSolicitud(LocalTime.of(11,0),LocalTime.of(11,30))),"Gestión personal"));assertEquals(2,respuesta.bloqueos().size());assertEquals(1,respuesta.citasCanceladas());assertEquals("600123123",respuesta.citasAfectadas().getFirst().telefonoCliente());verify(dias,times(2)).save(any(DiaBloqueado.class));}
 @Test @DisplayName("Un empleado consulta el calendario del equipo pero solo modifica el suyo") void debeConsultarCalendarioEquipoSinGestionarAjeno()throws Exception{Profesional pepe=new Profesional(barberia,"Pepe","pepe");id(pepe,20L);HorarioTrabajo horarioMimi=new HorarioTrabajo(barberia,mimi,DayOfWeek.MONDAY,LocalTime.of(9,0),LocalTime.of(14,0));HorarioTrabajo horarioPepe=new HorarioTrabajo(barberia,pepe,DayOfWeek.TUESDAY,LocalTime.of(10,0),LocalTime.of(15,0));when(horarios.findByBarberiaIdOrderByDiaSemanaAscHoraInicioAsc(1L)).thenReturn(List.of(horarioMimi,horarioPepe));when(citas.findByBarberiaIdAndEstadoOrderByFechaInicioAsc(1L,EstadoCita.CONFIRMADA)).thenReturn(List.of(cita));assertEquals(2,servicio.listarHorarios(barbero).size());assertEquals(1,servicio.listarOcupacionesEquipo(barbero).size());when(profesionales.findByIdAndBarberiaId(20L,1L)).thenReturn(Optional.of(pepe));assertThrows(AccesoNoAutorizadoExcepcion.class,()->servicio.crearHorario(barbero,new SolicitudHorario(20L,DayOfWeek.WEDNESDAY,LocalTime.of(9,0),LocalTime.of(13,0))));}
 @Test @DisplayName("La rutina completa se reemplaza en una única operación") void debeReemplazarRutinaCompleta()throws Exception{HorarioTrabajo anterior=new HorarioTrabajo(barberia,mimi,DayOfWeek.MONDAY,LocalTime.of(8,0),LocalTime.of(14,0));when(profesionales.findByIdAndBarberiaId(2L,1L)).thenReturn(Optional.of(mimi));when(barberias.findById(1L)).thenReturn(Optional.of(barberia));when(horarios.findByBarberiaIdOrderByDiaSemanaAscHoraInicioAsc(1L)).thenReturn(List.of(anterior));when(horarios.saveAll(anyList())).thenAnswer(i->i.getArgument(0));var tramos=List.of(new TramoRutinaSolicitud(DayOfWeek.MONDAY,LocalTime.of(9,0),LocalTime.of(14,0)),new TramoRutinaSolicitud(DayOfWeek.MONDAY,LocalTime.of(15,0),LocalTime.of(20,0)));assertEquals(2,servicio.reemplazarRutina(propietario,new SolicitudRutinaSemanal(2L,tramos,45,60)).size());assertEquals(45,barberia.getIntervaloMinutos());assertEquals(60,barberia.getDiasAntelacionReserva());verify(horarios).deleteAll(List.of(anterior));verify(horarios).flush();verify(horarios).saveAll(anyList());}
 private UsuarioAutenticado principal(RolUsuario rol,Long profesionalId){return new UsuarioAutenticado(9L,1L,"Barbería Mimi","barberia-mimi",profesionalId,"Mimi","usuario","hash",rol,true,true);}
 private static void id(Object o,Long valor)throws Exception{Field f=o.getClass().getDeclaredField("id");f.setAccessible(true);f.set(o,valor);}
}
