package com.barberiamimi.gestioncitas.controlador;
import com.barberiamimi.gestioncitas.servicio.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.*;
import org.springframework.http.MediaType;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;
import com.barberiamimi.gestioncitas.seguridad.UsuarioAutenticado;
import com.barberiamimi.gestioncitas.enumeracion.RolUsuario;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.authentication;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
import static org.junit.jupiter.api.Assertions.assertEquals;

@WebMvcTest({ControladorAdministracionCitas.class,ControladorAdministracionCatalogo.class,ControladorAdministracionAgenda.class,ControladorAdministracionNotificaciones.class})
@AutoConfigureMockMvc(addFilters=false)
class ControladoresAdministracionPrueba {
 @Autowired MockMvc mvc; @MockitoBean ServicioAdministracion administracion; @MockitoBean ServicioCitas citas;
 @Test @DisplayName("Debe exponer el contrato administrativo de citas") void debeExponerCitas()throws Exception{mvc.perform(get("/api/administracion/citas")).andExpect(status().isOk());mvc.perform(get("/api/administracion/citas/1")).andExpect(status().isOk());String cuerpo="{\"nombreCliente\":\"Ana\",\"telefonoCliente\":\"600123123\",\"servicioId\":1,\"profesionalId\":1,\"fechaInicio\":\"2030-09-10T10:00:00\"}";UsuarioAutenticado u=new UsuarioAutenticado(1L,1L,"Mimi","mimi",null,null,"duena","hash",RolUsuario.PROPIETARIO,true,true);var solicitud=new com.barberiamimi.gestioncitas.dto.solicitud.SolicitudCrearCita("Ana","600123123",null,1L,1L,java.time.LocalDateTime.of(2030,9,10,10,0),null);assertEquals(201,new ControladorAdministracionCitas(administracion,citas).crear(u,"clave",solicitud).getStatusCode().value());mvc.perform(put("/api/administracion/citas/1").contentType(MediaType.APPLICATION_JSON).content(cuerpo)).andExpect(status().isOk());mvc.perform(patch("/api/administracion/citas/1/estado").contentType(MediaType.APPLICATION_JSON).content("{\"estado\":\"COMPLETADA\"}")).andExpect(status().isOk());mvc.perform(post("/api/administracion/citas/1/cancelacion")).andExpect(status().isOk());}
 @Test @DisplayName("Debe exponer el contrato administrativo del catálogo") void debeExponerCatalogo()throws Exception{mvc.perform(get("/api/administracion/servicios")).andExpect(status().isOk());String s="{\"nombre\":\"Corte\",\"precio\":15,\"duracionMinutos\":30}";mvc.perform(post("/api/administracion/servicios").contentType(MediaType.APPLICATION_JSON).content(s)).andExpect(status().isCreated());mvc.perform(put("/api/administracion/servicios/1").contentType(MediaType.APPLICATION_JSON).content(s)).andExpect(status().isOk());mvc.perform(patch("/api/administracion/servicios/1/estado").contentType(MediaType.APPLICATION_JSON).content("{\"activo\":false}")).andExpect(status().isOk());mvc.perform(get("/api/administracion/profesionales")).andExpect(status().isOk());String p="{\"nombre\":\"Mimi\",\"alias\":\"mimi\"}";mvc.perform(post("/api/administracion/profesionales").contentType(MediaType.APPLICATION_JSON).content(p)).andExpect(status().isCreated());mvc.perform(put("/api/administracion/profesionales/1").contentType(MediaType.APPLICATION_JSON).content(p)).andExpect(status().isOk());mvc.perform(patch("/api/administracion/profesionales/1/estado").contentType(MediaType.APPLICATION_JSON).content("{\"activo\":true}")).andExpect(status().isOk());mvc.perform(post("/api/administracion/usuarios").contentType(MediaType.APPLICATION_JSON).content("{\"nombreUsuario\":\"barbero\",\"contrasena\":\"contrasena-segura\",\"rol\":\"BARBERO\",\"profesionalId\":1}")).andExpect(status().isCreated());mvc.perform(patch("/api/administracion/usuarios/1/contrasena").contentType(MediaType.APPLICATION_JSON).content("{\"nuevaContrasena\":\"nueva-contrasena\"}")).andExpect(status().isOk());}
 @Test @DisplayName("Debe exponer horarios, bloqueos y notificaciones") void debeExponerAgenda()throws Exception{mvc.perform(get("/api/administracion/horarios")).andExpect(status().isOk());String h="{\"profesionalId\":1,\"diaSemana\":\"MONDAY\",\"horaInicio\":\"09:00:00\",\"horaFin\":\"14:00:00\"}";mvc.perform(post("/api/administracion/horarios").contentType(MediaType.APPLICATION_JSON).content(h)).andExpect(status().isCreated());mvc.perform(put("/api/administracion/horarios/1").contentType(MediaType.APPLICATION_JSON).content(h)).andExpect(status().isOk());mvc.perform(delete("/api/administracion/horarios/1")).andExpect(status().isNoContent());mvc.perform(get("/api/administracion/dias-bloqueados")).andExpect(status().isOk());String d="{\"profesionalId\":1,\"fecha\":\"2030-12-24\",\"motivo\":\"Cierre\"}";mvc.perform(post("/api/administracion/dias-bloqueados").contentType(MediaType.APPLICATION_JSON).content(d)).andExpect(status().isCreated());mvc.perform(put("/api/administracion/dias-bloqueados/1").contentType(MediaType.APPLICATION_JSON).content(d)).andExpect(status().isOk());mvc.perform(delete("/api/administracion/dias-bloqueados/1")).andExpect(status().isNoContent());mvc.perform(get("/api/administracion/notificaciones")).andExpect(status().isOk());mvc.perform(patch("/api/administracion/notificaciones/1/leida")).andExpect(status().isOk());}
}
